name: catalog-service -> YC Serverless

on:
  push:
    branches: ["main", "master"]
    paths:
      - "services/catalog-service/**"
      - ".github/workflows/catalog-yc-deploy.yml"

jobs:
  build-and-push-to-yc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to YC Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Build & Push image to YC Registry (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: ./services/catalog-service
          file: ./services/catalog-service/Dockerfile
          push: true
          tags: |
            cr.yandex/${{ secrets.YC_REGISTRY_ID }}/catalog-service:latest
            cr.yandex/${{ secrets.YC_REGISTRY_ID }}/catalog-service:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-to-yc]
    steps:
      - name: Deploy serverless container revision
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME_CATALOG }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/catalog-service:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-env: |
            PORT=8080
